src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     * @Assert\GreaterThanOrEqual("today")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $all_day;

    /**
     * @ORM\Column(type="string", length=7)
     * @Assert\NotBlank
     */
    private $border_color;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }
}

src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\LessThan;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('start',DateTimeType::class,[
                'date_widget'=>'single_text',
                'constraints' => [
                    new LessThanOrEqual([
                        'propertyPath' => 'parent.all[start].data'
                    ]),
                ],
               
            ])
            ->add('end',DateTimeType::class,[
                'constraints' => [
                    new GreaterThanOrEqual([
                        'propertyPath' => 'parent.all[start].data'
                    ]),
                ],
                'date_widget'=>'single_text',
                
            ])
            ->add('description')
            ->add('all_day')
            ->add('border_color',ColorType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

templates/calendar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit evenement{% endblock %}

{% block body %}
    <h1> Edit evenement</h1>

    {{ form_start(form) }}

    {{ form_row(form.title) }}
    {{ form_row(form.start) }}
    {{ form_row(form.end) }}
    {{ form_row(form.description) }}
    {{ form_row(form.all_day) }}
    {{ form_row(form.border_color) }}

    <button class="btn">{{ button_label|default('Edit un evenement') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('calendar_index') }}">back to list</a>
{% endblock %}

templates/calendar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar index{% endblock %}

{% block body %}
    <h1>Calendar index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>All_day</th>
                <th>Border_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calendar in calendars %}
            <tr>
                <td>{{ calendar.id }}</td>
                <td>{{ calendar.title }}</td>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.description }}</td>
                <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>
                <td>{{ calendar.borderColor }}</td>
                <td>
                    <a href="{{ path('afficher_un', {'id': calendar.id}) }}">show</a>
                    <a href="{{ path('modifier', {'id': calendar.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ajouterE') }}">Create new</a>

    <hr>
    <a href="{{ path('main') }}">Calendar</a>
{% endblock %}

templates/calendar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau evenement{% endblock %}

{% block body %}
    <h1>Creer un nouveau evenement</h1>

    {{ form_start(form) }}

    {{ form_row(form.title) }}
    {{ form_row(form.start) }}
    {{ form_row(form.end) }}
    {{ form_row(form.description) }}
    {{ form_row(form.all_day) }}
    {{ form_row(form.border_color) }}

    <button class="btn">{{ button_label|default('Ajouter un evenement') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('calendar_index') }}">back to list</a>
{% endblock %}

templates/calendar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block body %}
    <h1>Calendar</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ calendar.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ calendar.title }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ calendar.description }}</td>
            </tr>
            <tr>
                <th>All_day</th>
                <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Border_color</th>
                <td>{{ calendar.borderColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('calendar_index') }}">back to list</a>

    <a href="{{ path('modifier', {'id': calendar.id}) }}">edit</a>
    <a href="{{ path('supprimer', {'id': calendar.id}) }}">supprimer</a>

   
{% endblock %}